apiVersion: v1
kind: Service
metadata:
  name: webapp-headless
  namespace: stage1
  labels:
    app: webapp
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  clusterIP: None
  selector:
    app: webapp