---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
  namespace: stage2
spec:
  # replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - image: nginx:1.20.2-alpine
        name: webapp
        ports:
        - containerPort: 80
