---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp2
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: webapp2
    repoURL: https://github.com/constantine-kutenko/gitops-kubernetes-poc.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
  - group: ""
    kind: Deployment
    jsonPointers:
    - /spec/replicas
    - /spec/template/spec/containers/image
    - /spec/template/metadata/labels/version_api
    - /spec/template/metadata/labels/version_nginx
