---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp2
  namespace: qa3
spec:
  maxReplicas: 4
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: webapp2

