---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp1
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: webapp1
    repoURL: https://github.com/constantine-kutenko/gitops-kubernetes-poc.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: webapp1
    jsonPointers:
    - /spec/replicas
